import type { ComponentContract, InteractionContract, TokenRegistry } from "../schemas/normal-form.ts";
import type { CanonicalNode, CanonicalPageSpec } from "./types.ts";

type NodeInput = Omit<CanonicalNode, "attributes" | "styles" | "conditionalStyles" | "children"> & {
  attributes?: Record<string, string>;
  styles?: Record<string, string>;
  conditionalStyles?: CanonicalNode["conditionalStyles"];
  children?: CanonicalNode[];
};

function node(input: NodeInput): CanonicalNode {
  return { attributes: {}, styles: {}, conditionalStyles: [], children: [], ...input };
}

const stackAtMobile = (styles: Record<string, string>): CanonicalNode["conditionalStyles"] => [{
  condition: { states: [], media: ["(max-width: 47.99rem)"], supports: [] },
  styles,
}];

const tokens: TokenRegistry = {
  schemaVersion: "dtcg-2025-10+gen2prod-0.1.0",
  conformsTo: ["DTCG Format Module 2025.10", "DTCG Color Module 2025.10"],
  adapterSchema: "gen2prod-token-adapter-0.1.0",
  tokens: [
    { id: "spacing.s", name: "spacing.s", type: "dimension", category: "spacing", value: { value: 0.75, unit: "rem" }, runtimeVariable: "--space-s", runtimeExpression: "var(--space-s)", semanticRole: "compact-spacing", allowedProperties: ["gap", "padding", "margin"], source: "fixture", status: "active", sampledValues: { "default@1280": "12px" } },
    { id: "spacing.m", name: "spacing.m", type: "dimension", category: "spacing", value: { value: 1, unit: "rem" }, runtimeVariable: "--space-m", runtimeExpression: "var(--space-m)", semanticRole: "content-spacing", allowedProperties: ["gap", "padding", "margin"], source: "fixture", status: "active", sampledValues: { "default@1280": "16px" } },
    { id: "spacing.l", name: "spacing.l", type: "dimension", category: "spacing", value: { value: 2, unit: "rem" }, runtimeVariable: "--space-l", runtimeExpression: "var(--space-l)", semanticRole: "component-spacing", allowedProperties: ["gap", "padding", "margin"], source: "fixture", status: "active", sampledValues: { "default@1280": "32px" } },
    { id: "spacing.section", name: "spacing.section", type: "dimension", category: "section-spacing", value: { value: 5, unit: "rem" }, runtimeVariable: "--section-space", runtimeExpression: "var(--section-space)", semanticRole: "section-block-padding", allowedProperties: ["padding-block"], source: "fixture", status: "active", sampledValues: { "default@1280": "80px" } },
    { id: "color.text", name: "color.text", type: "color", category: "color", value: { colorSpace: "srgb", components: [0.08, 0.1, 0.16], alpha: 1 }, runtimeVariable: "--text-color", runtimeExpression: "var(--text-color)", semanticRole: "body-text", allowedProperties: ["color"], source: "fixture", status: "active", sampledValues: { "default@1280": "#141a29" } },
    { id: "color.surface", name: "color.surface", type: "color", category: "color", value: { colorSpace: "srgb", components: [1, 1, 1], alpha: 1 }, runtimeVariable: "--surface", runtimeExpression: "var(--surface)", semanticRole: "surface", allowedProperties: ["background-color"], source: "fixture", status: "active", sampledValues: { "default@1280": "#ffffff" } },
    { id: "color.canvas", name: "color.canvas", type: "color", category: "color", value: { colorSpace: "srgb", components: [0.96, 0.97, 0.99], alpha: 1 }, runtimeVariable: "--canvas", runtimeExpression: "var(--canvas)", semanticRole: "page-canvas", allowedProperties: ["background-color"], source: "fixture", status: "active", sampledValues: { "default@1280": "#f5f7fc" } },
    { id: "color.primary", name: "color.primary", type: "color", category: "color", value: { colorSpace: "srgb", components: [0.12, 0.3, 0.8], alpha: 1 }, runtimeVariable: "--primary", runtimeExpression: "var(--primary)", semanticRole: "primary-action", allowedProperties: ["color", "background-color", "outline-color"], source: "fixture", status: "active", sampledValues: { "default@1280": "#1f4dcc" } },
    { id: "color.on-primary", name: "color.on-primary", type: "color", category: "color", value: { colorSpace: "srgb", components: [1, 1, 1], alpha: 1 }, runtimeVariable: "--on-primary", runtimeExpression: "var(--on-primary)", semanticRole: "on-primary-text", allowedProperties: ["color"], source: "fixture", status: "active", sampledValues: { "default@1280": "#ffffff" } },
    { id: "radius.m", name: "radius.m", type: "dimension", category: "radius", value: { value: 0.75, unit: "rem" }, runtimeVariable: "--radius-m", runtimeExpression: "var(--radius-m)", semanticRole: "component-radius", allowedProperties: ["border-radius"], source: "fixture", status: "active", sampledValues: { "default@1280": "12px" } },
    { id: "sizing.content", name: "sizing.content", type: "dimension", category: "content-width", value: { value: 72, unit: "rem" }, runtimeVariable: "--content-width", runtimeExpression: "var(--content-width)", semanticRole: "page-content-width", allowedProperties: ["max-inline-size"], source: "fixture", status: "active", sampledValues: { "default@1280": "1152px" } },
    { id: "typography.h1", name: "typography.h1", type: "dimension", category: "typography", value: { value: 3, unit: "rem" }, runtimeVariable: "--h1", runtimeExpression: "var(--h1)", semanticRole: "page-title", allowedProperties: ["font-size"], source: "fixture", status: "active", sampledValues: { "default@1280": "48px" } },
    { id: "typography.h2", name: "typography.h2", type: "dimension", category: "typography", value: { value: 2, unit: "rem" }, runtimeVariable: "--h2", runtimeExpression: "var(--h2)", semanticRole: "section-title", allowedProperties: ["font-size"], source: "fixture", status: "active", sampledValues: { "default@1280": "32px" } },
    { id: "typography.body.large", name: "typography.body.large", type: "dimension", category: "typography", value: { value: 1.125, unit: "rem" }, runtimeVariable: "--text-l", runtimeExpression: "var(--text-l)", semanticRole: "large-body-copy", allowedProperties: ["font-size"], source: "fixture", status: "active", sampledValues: { "default@1280": "1.125rem" } },
    { id: "typography.card.title", name: "typography.card.title", type: "dimension", category: "typography", value: { value: 1.25, unit: "rem" }, runtimeVariable: "--card-title-size", runtimeExpression: "var(--card-title-size)", semanticRole: "card-title", allowedProperties: ["font-size"], source: "fixture", status: "active", sampledValues: { "default@1280": "1.25rem" } },
    { id: "typography.heading.tight", name: "typography.heading.tight", type: "number", category: "typography", value: 1.05, runtimeVariable: "--heading-line-height-tight", runtimeExpression: "var(--heading-line-height-tight)", semanticRole: "tight-heading-line-height", allowedProperties: ["line-height"], source: "fixture", status: "active", sampledValues: { "default@1280": "1.05" } },
    { id: "typography.heading.default", name: "typography.heading.default", type: "number", category: "typography", value: 1.15, runtimeVariable: "--heading-line-height", runtimeExpression: "var(--heading-line-height)", semanticRole: "heading-line-height", allowedProperties: ["line-height"], source: "fixture", status: "active", sampledValues: { "default@1280": "1.15" } },
    { id: "typography.family.body", name: "typography.family.body", type: "fontFamily", category: "typography", value: "system-ui, sans-serif", runtimeVariable: "--body-font-family", runtimeExpression: "var(--body-font-family)", semanticRole: "body-font-family", allowedProperties: ["font-family"], source: "fixture", status: "active", sampledValues: { "default@1280": "system-ui, sans-serif" } },
    { id: "typography.weight.bold", name: "typography.weight.bold", type: "fontWeight", category: "typography", value: 700, runtimeVariable: "--font-weight-bold", runtimeExpression: "var(--font-weight-bold)", semanticRole: "bold-text", allowedProperties: ["font-weight"], source: "fixture", status: "active", sampledValues: { "default@1280": "700" } },
  ],
};

const sharedStyles = {
  page: { "font-family": "system-ui, sans-serif", color: "var(--text-color)", "background-color": "var(--canvas)", margin: "0" },
  section: { "padding-block": "var(--section-space)", "padding-inline": "var(--space-m)" },
  inner: { "max-inline-size": "var(--content-width)", "margin-inline": "auto" },
  title: { "font-size": "var(--h1)", "line-height": "1.05", margin: "0" },
  sectionTitle: { "font-size": "var(--h2)", "line-height": "1.15", margin: "0" },
  button: { display: "inline-flex", padding: "var(--space-s) var(--space-m)", "border-radius": "var(--radius-m)", "background-color": "var(--primary)", color: "var(--on-primary)", "text-decoration": "none" },
  card: { padding: "var(--space-l)", "border-radius": "var(--radius-m)", "background-color": "var(--surface)" },
};

function contract(name: string, type: "component" | "section", elements: string[], variants: string[] = []): ComponentContract {
  return {
    name,
    type,
    description: `${name} fixture contract`,
    props: { title: { type: "string", required: true } },
    variants,
    states: ["default", "focus-visible"],
    slots: elements,
    bem: { block: name, elements, modifiers: variants },
  };
}

function base(id: string, archetype: CanonicalPageSpec["archetype"], root: CanonicalNode, components: ComponentContract[], interactions: InteractionContract[] = []): CanonicalPageSpec {
  return {
    schemaVersion: "0.1.0",
    id,
    archetype,
    domain: "synthetic-productivity-software",
    intent: { pageGoal: `Demonstrate ${archetype}`, audience: "small product teams", conversionGoal: "start a trial", seoIntent: `${archetype} productivity software` },
    components,
    tokens,
    root,
    interactions,
    viewports: [360, 768, 1280, 1440],
  };
}

function page(children: CanonicalNode[]): CanonicalNode {
  return node({ nodeId: "page", tag: "body", role: "document", classes: ["page"], styles: sharedStyles.page, children: [node({ nodeId: "main", tag: "main", role: "main", classes: [], children })] });
}

export function createArchetypes(): CanonicalPageSpec[] {
  const buttonContract = contract("button", "component", ["label"], ["primary", "secondary"]);
  const hero = base("hero-cta", "hero-cta", page([
    node({ nodeId: "hero", tag: "section", role: "primary-intro", classes: ["hero", "hero--split"], attributes: { "aria-labelledby": "hero-title" }, styles: sharedStyles.section, children: [
      node({ nodeId: "hero-inner", tag: "div", role: "layout-container", classes: ["hero__inner"], styles: { ...sharedStyles.inner, display: "grid", gap: "var(--space-l)", "grid-template-columns": "repeat(2, minmax(0, 1fr))" }, conditionalStyles: stackAtMobile({ "grid-template-columns": "1fr" }), children: [
        node({ nodeId: "hero-content", tag: "div", role: "content-stack", classes: ["hero__content"], styles: { display: "grid", gap: "var(--space-m)" }, children: [
          node({ nodeId: "hero-title", tag: "h1", role: "primary-heading", classes: ["hero__title"], attributes: { id: "hero-title" }, text: "Ship a calmer workday", styles: sharedStyles.title }),
          node({ nodeId: "hero-lede", tag: "p", role: "supporting-copy", classes: ["hero__lede"], text: "Plan, focus, and finish meaningful work without the busywork.", styles: { margin: "0", "font-size": "1.125rem" } }),
          node({ nodeId: "hero-actions", tag: "div", role: "cta-group", classes: ["hero__actions"], styles: { display: "flex", gap: "var(--space-s)" }, children: [
            node({ nodeId: "hero-cta", tag: "a", role: "primary-cta", classes: ["button", "button--primary"], attributes: { href: "/start", "data-hook": "analytics:primary-cta" }, text: "Start free", styles: sharedStyles.button }),
          ] }),
        ] }),
        node({ nodeId: "hero-media", tag: "div", role: "visual-proof", classes: ["hero__media"], styles: sharedStyles.card, children: [
          node({ nodeId: "hero-image", tag: "img", role: "meaningful-image", classes: ["hero__image"], attributes: { src: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='640' height='400'%3E%3Crect width='640' height='400' fill='%23dbe5ff'/%3E%3C/svg%3E", alt: "Product dashboard with a prioritized task list", width: "640", height: "400" }, styles: { display: "block", "inline-size": "100%", "border-radius": "var(--radius-m)" } }),
        ] }),
      ] }),
    ] }),
  ]), [contract("hero", "section", ["inner", "content", "title", "lede", "actions", "media", "image"], ["split"]), buttonContract], [{ component: "button", nodeId: "hero-cta", kind: "link", keyboard: ["Enter activates navigation"], focusManagement: "native link focus", stateAttributes: [], reducedMotion: "no motion" }]);

  const featureItems = ["Clear priorities", "Protected focus", "Visible progress"].map((title, index) => node({ nodeId: `feature-${index + 1}`, tag: "li", role: "feature-item", classes: ["feature-grid__item", "feature-card"], styles: sharedStyles.card, children: [
    node({ nodeId: `feature-${index + 1}-title`, tag: "h2", role: "card-heading", classes: ["feature-card__title"], text: title, styles: { margin: "0", "font-size": "1.25rem" } }),
    node({ nodeId: `feature-${index + 1}-text`, tag: "p", role: "card-copy", classes: ["feature-card__text"], text: "A consistent system keeps the team moving.", styles: { margin: "var(--space-s) 0 0" } }),
  ] }));
  const features = base("feature-grid", "feature-grid", page([node({ nodeId: "features", tag: "section", role: "product-features", classes: ["feature-grid"], attributes: { "aria-labelledby": "features-title" }, styles: sharedStyles.section, children: [
    node({ nodeId: "features-inner", tag: "div", role: "layout-container", classes: ["feature-grid__inner"], styles: sharedStyles.inner, children: [
      node({ nodeId: "features-title", tag: "h1", role: "primary-heading", classes: ["feature-grid__title"], attributes: { id: "features-title" }, text: "Everything needed to move forward", styles: sharedStyles.sectionTitle }),
      node({ nodeId: "features-list", tag: "ul", role: "feature-list", classes: ["feature-grid__list"], styles: { display: "grid", gap: "var(--space-m)", "grid-template-columns": "repeat(3, minmax(0, 1fr))", "list-style": "none", padding: "0", margin: "0" }, conditionalStyles: stackAtMobile({ "grid-template-columns": "1fr" }), children: featureItems }),
    ] }),
  ] })]), [contract("feature-grid", "section", ["inner", "title", "list", "item"]), contract("feature-card", "component", ["title", "text"])]);

  const priceCards = ["Starter", "Team", "Scale"].map((title, index) => node({ nodeId: `plan-${index}`, tag: "li", role: "pricing-plan", classes: ["pricing__item", "pricing-card", ...(index === 1 ? ["pricing-card--featured"] : [])], styles: sharedStyles.card, children: [
    node({ nodeId: `plan-${index}-title`, tag: "h2", role: "plan-heading", classes: ["pricing-card__title"], text: title, styles: { margin: "0" } }),
    node({ nodeId: `plan-${index}-price`, tag: "p", role: "plan-price", classes: ["pricing-card__price"], text: `$${[9, 24, 79][index]}/month`, styles: { "font-size": "var(--h2)" } }),
    node({ nodeId: `plan-${index}-cta`, tag: "a", role: "plan-cta", classes: ["button", "button--primary"], attributes: { href: `/start?plan=${title.toLowerCase()}` }, text: "Choose plan", styles: sharedStyles.button }),
  ] }));
  const pricing = base("pricing", "pricing", page([node({ nodeId: "pricing", tag: "section", role: "pricing", classes: ["pricing"], attributes: { "aria-labelledby": "pricing-title" }, styles: sharedStyles.section, children: [node({ nodeId: "pricing-inner", tag: "div", role: "layout-container", classes: ["pricing__inner"], styles: sharedStyles.inner, children: [node({ nodeId: "pricing-title", tag: "h1", role: "primary-heading", classes: ["pricing__title"], attributes: { id: "pricing-title" }, text: "Simple pricing", styles: sharedStyles.title }), node({ nodeId: "pricing-list", tag: "ul", role: "plan-list", classes: ["pricing__list"], styles: { display: "grid", gap: "var(--space-m)", "grid-template-columns": "repeat(3, minmax(0, 1fr))", "list-style": "none", padding: "0", margin: "0" }, conditionalStyles: stackAtMobile({ "grid-template-columns": "1fr" }), children: priceCards })] })] })]), [contract("pricing", "section", ["inner", "title", "list", "item"]), contract("pricing-card", "component", ["title", "price", "action"], ["featured"]), buttonContract]);

  const faq = base("faq", "faq", page([node({ nodeId: "faq", tag: "section", role: "frequently-asked-questions", classes: ["faq"], attributes: { "aria-labelledby": "faq-title" }, styles: sharedStyles.section, children: [node({ nodeId: "faq-inner", tag: "div", role: "layout-container", classes: ["faq__inner"], styles: sharedStyles.inner, children: [node({ nodeId: "faq-title", tag: "h1", role: "primary-heading", classes: ["faq__title"], attributes: { id: "faq-title" }, text: "Questions, answered", styles: sharedStyles.title }), ...["Can I cancel anytime?", "Does it work offline?"].map((question, index) => node({ nodeId: `faq-item-${index}`, tag: "details", role: "disclosure", classes: ["faq__item"], styles: sharedStyles.card, children: [node({ nodeId: `faq-summary-${index}`, tag: "summary", role: "disclosure-button", classes: ["faq__question"], text: question, styles: { cursor: "pointer", "font-weight": "700" } }), node({ nodeId: `faq-answer-${index}`, tag: "p", role: "disclosure-panel", classes: ["faq__answer"], text: "Yes. Your data remains available on your terms.", styles: { margin: "var(--space-s) 0 0" } })] }))] })] })]), [contract("faq", "section", ["inner", "title", "item", "question", "answer"])], [{ component: "faq", nodeId: "faq-item-0", kind: "disclosure", keyboard: ["Enter or Space toggles"], focusManagement: "focus remains on summary", stateAttributes: ["open"], reducedMotion: "no motion required" }]);

  const testimonial = base("testimonial", "testimonial", page([node({ nodeId: "testimonial", tag: "section", role: "customer-proof", classes: ["testimonial"], attributes: { "aria-labelledby": "testimonial-title" }, styles: sharedStyles.section, children: [node({ nodeId: "testimonial-inner", tag: "div", role: "layout-container", classes: ["testimonial__inner"], styles: sharedStyles.inner, children: [node({ nodeId: "testimonial-title", tag: "h1", role: "primary-heading", classes: ["testimonial__title"], attributes: { id: "testimonial-title" }, text: "Loved by focused teams", styles: sharedStyles.title }), node({ nodeId: "quote", tag: "figure", role: "testimonial-quote", classes: ["testimonial-card"], styles: { ...sharedStyles.card, margin: "0" }, children: [node({ nodeId: "quote-text", tag: "blockquote", role: "quote", classes: ["testimonial-card__quote"], text: "We finally know what deserves attention each morning.", styles: { margin: "0", "font-size": "1.25rem" } }), node({ nodeId: "quote-attribution", tag: "figcaption", role: "attribution", classes: ["testimonial-card__attribution"], text: "Mina Chen, Northstar", styles: { "margin-block-start": "var(--space-s)" } })] })] })] })]), [contract("testimonial", "section", ["inner", "title"]), contract("testimonial-card", "component", ["quote", "attribution"])]);

  const navigation = base("navigation", "navigation", page([node({ nodeId: "site-header", tag: "header", role: "site-header", classes: ["site-header"], styles: { padding: "var(--space-m)", "background-color": "var(--surface)" }, children: [node({ nodeId: "primary-nav", tag: "nav", role: "primary-navigation", classes: ["site-header__nav"], attributes: { "aria-label": "Primary" }, styles: sharedStyles.inner, children: [node({ nodeId: "nav-list", tag: "ul", role: "navigation-list", classes: ["site-header__list"], styles: { display: "flex", gap: "var(--space-m)", "list-style": "none", padding: "0", margin: "0" }, conditionalStyles: stackAtMobile({ "flex-direction": "column" }), children: ["Product", "Pricing", "About"].map((label, index) => node({ nodeId: `nav-item-${index}`, tag: "li", role: "navigation-item", classes: ["site-header__item"], children: [node({ nodeId: `nav-link-${index}`, tag: "a", role: "navigation-link", classes: ["site-header__link"], attributes: { href: `/${label.toLowerCase()}` }, text: label, styles: { color: "var(--text-color)" } })] })) })] })] }), node({ nodeId: "navigation-title", tag: "h1", role: "primary-heading", classes: ["page__title"], text: "Navigation", styles: sharedStyles.title })]), [contract("site-header", "section", ["nav", "list", "item", "link"])], [{ component: "site-header", nodeId: "primary-nav", kind: "navigation", keyboard: ["Tab reaches links", "Enter navigates"], focusManagement: "native link focus", stateAttributes: [], reducedMotion: "no motion" }]);

  const form = base("form", "form", page([node({ nodeId: "contact", tag: "section", role: "contact-form-region", classes: ["contact"], attributes: { "aria-labelledby": "contact-title" }, styles: sharedStyles.section, children: [node({ nodeId: "contact-inner", tag: "div", role: "layout-container", classes: ["contact__inner"], styles: sharedStyles.inner, children: [node({ nodeId: "contact-title", tag: "h1", role: "primary-heading", classes: ["contact__title"], attributes: { id: "contact-title" }, text: "Tell us about your team", styles: sharedStyles.title }), node({ nodeId: "contact-form", tag: "form", role: "contact-form", classes: ["contact-form"], attributes: { action: "/contact", method: "post" }, styles: { display: "grid", gap: "var(--space-m)" }, children: [node({ nodeId: "email-label", tag: "label", role: "field-label", classes: ["contact-form__label"], attributes: { for: "email" }, text: "Work email", styles: {} }), node({ nodeId: "email-input", tag: "input", role: "email-field", classes: ["contact-form__input"], attributes: { id: "email", name: "email", type: "email", required: "" }, styles: { padding: "var(--space-s)", "border-radius": "var(--radius-m)" } }), node({ nodeId: "form-submit", tag: "button", role: "submit", classes: ["button", "button--primary"], attributes: { type: "submit" }, text: "Request a demo", styles: sharedStyles.button })] })] })] })]), [contract("contact", "section", ["inner", "title"]), contract("contact-form", "component", ["label", "input"]), buttonContract], [{ component: "contact-form", nodeId: "contact-form", kind: "form", keyboard: ["Tab follows source order", "Enter submits"], focusManagement: "invalid field receives focus", stateAttributes: ["aria-invalid"], reducedMotion: "no motion" }]);

  const dialog = base("dialog", "dialog", page([node({ nodeId: "dialog-demo", tag: "section", role: "dialog-demonstration", classes: ["dialog-demo"], attributes: { "aria-labelledby": "dialog-demo-title" }, styles: sharedStyles.section, children: [node({ nodeId: "dialog-demo-inner", tag: "div", role: "layout-container", classes: ["dialog-demo__inner"], styles: sharedStyles.inner, children: [
    node({ nodeId: "dialog-demo-title", tag: "h1", role: "primary-heading", classes: ["dialog-demo__title"], attributes: { id: "dialog-demo-title" }, text: "Review before publishing", styles: sharedStyles.title }),
    node({ nodeId: "dialog-demo-copy", tag: "p", role: "supporting-copy", classes: ["dialog-demo__copy"], text: "Confirm ownership, visibility, and timing without losing your place.", styles: { "font-size": "var(--text-l)" } }),
    node({ nodeId: "dialog-trigger", tag: "button", role: "dialog-trigger", classes: ["button", "button--primary"], attributes: { type: "button", "aria-haspopup": "dialog", "aria-controls": "publish-dialog" }, text: "Review publication", styles: sharedStyles.button, conditionalStyles: [{ condition: { states: ["hover"], media: [], supports: [] }, styles: { "outline-color": "var(--primary)" } }] }),
    node({ nodeId: "publish-dialog", tag: "dialog", role: "confirmation-dialog", classes: ["publish-dialog"], attributes: { id: "publish-dialog", "aria-labelledby": "publish-dialog-title", "aria-describedby": "publish-dialog-description" }, styles: { padding: "var(--space-l)", "border-radius": "var(--radius-m)", "background-color": "var(--surface)", color: "var(--text-color)", "max-inline-size": "var(--content-width)" }, children: [
      node({ nodeId: "publish-dialog-title", tag: "h2", role: "dialog-heading", classes: ["publish-dialog__title"], attributes: { id: "publish-dialog-title" }, text: "Publish this workspace?", styles: sharedStyles.sectionTitle }),
      node({ nodeId: "publish-dialog-description", tag: "p", role: "dialog-description", classes: ["publish-dialog__description"], attributes: { id: "publish-dialog-description" }, text: "Everyone with access will see the approved plan and its current status.", styles: { "margin-block": "var(--space-m)" } }),
      node({ nodeId: "publish-dialog-actions", tag: "form", role: "dialog-actions", classes: ["publish-dialog__actions"], attributes: { method: "dialog" }, styles: { display: "flex", gap: "var(--space-s)" }, children: [node({ nodeId: "publish-dialog-cancel", tag: "button", role: "dialog-cancel", classes: ["button", "button--secondary"], attributes: { type: "submit", value: "cancel" }, text: "Keep editing", styles: sharedStyles.button }), node({ nodeId: "publish-dialog-confirm", tag: "button", role: "dialog-confirm", classes: ["button", "button--primary"], attributes: { type: "submit", value: "confirm" }, text: "Publish", styles: sharedStyles.button })] }),
    ] }),
  ] })] })]), [contract("dialog-demo", "section", ["inner", "title", "copy"]), contract("publish-dialog", "component", ["title", "description", "actions"]), buttonContract], [{ component: "publish-dialog", nodeId: "publish-dialog", kind: "dialog", keyboard: ["Trigger opens dialog", "Tab remains inside while modal", "Escape closes without publishing"], focusManagement: "move focus to the dialog heading on open and restore it to the trigger on close", stateAttributes: ["open", "aria-haspopup", "aria-controls"], reducedMotion: "opening and closing remain understandable with no motion" }]);

  const articleSections = [
    ["long-form-foundations", "Start with a shared definition", "A production system needs explicit authority for content, behavior, pixels, tokens, and acceptance. Ambiguity in any one layer becomes churn later."],
    ["long-form-evidence", "Gather evidence before rewriting", "Capture rendered layout, accessible names, responsive states, and interaction contracts before choosing a component boundary."],
    ["long-form-verification", "Verify the smallest safe change", "Recompile the typed plan, compare the browser render, and keep only changes that improve the constrained fitness vector."],
    ["long-form-learning", "Feed outcomes back into the loop", "Store accepted and rejected trajectories with project isolation so future selectors and verifiers learn without leaking the holdout."],
  ].map(([id, heading, copy], index) => node({ nodeId: id!, tag: "section", role: "article-section", classes: ["field-guide__section"], attributes: { "aria-labelledby": `${id}-title` }, styles: { "margin-block-start": "var(--space-l)" }, children: [node({ nodeId: `${id}-title`, tag: "h2", role: "section-heading", classes: ["field-guide__heading"], attributes: { id: `${id}-title` }, text: heading!, styles: sharedStyles.sectionTitle }), node({ nodeId: `${id}-copy`, tag: "p", role: "section-copy", classes: ["field-guide__copy"], text: copy!, styles: { "font-size": "var(--text-l)" } }), ...(index === 1 ? [node({ nodeId: "long-form-checklist", tag: "ul", role: "evidence-checklist", classes: ["field-guide__checklist"], styles: { display: "grid", gap: "var(--space-s)", "padding-inline-start": "var(--space-l)" }, children: ["Desktop and mobile layout", "Default, focus, hover, and open states", "Content and behavior authority"].map((text, item) => node({ nodeId: `long-form-check-${item}`, tag: "li", role: "checklist-item", classes: ["field-guide__checklist-item"], text, styles: {} })) })] : [])] }));
  const longForm = base("long-form", "long-form", page([node({ nodeId: "field-guide", tag: "article", role: "long-form-guide", classes: ["field-guide"], attributes: { "aria-labelledby": "field-guide-title" }, styles: sharedStyles.section, children: [node({ nodeId: "field-guide-inner", tag: "div", role: "layout-container", classes: ["field-guide__inner"], styles: { ...sharedStyles.inner, "max-inline-size": "var(--content-width)" }, children: [node({ nodeId: "field-guide-header", tag: "header", role: "article-header", classes: ["field-guide__header"], styles: { "padding-block-end": "var(--space-l)" }, children: [node({ nodeId: "field-guide-title", tag: "h1", role: "primary-heading", classes: ["field-guide__title"], attributes: { id: "field-guide-title" }, text: "A field guide to measured website reconstruction", styles: sharedStyles.title }), node({ nodeId: "field-guide-lede", tag: "p", role: "supporting-copy", classes: ["field-guide__lede"], text: "Turn a visual reference or inherited frontend into maintainable production code without guessing away its intent.", styles: { "font-size": "var(--text-l)" } })] }), ...articleSections] })] })]), [contract("field-guide", "section", ["inner", "header", "title", "lede", "section", "heading", "copy", "checklist", "checklist-item"])]);

  const wideImage = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1200' height='675'%3E%3Crect width='1200' height='675' fill='%23dbe5ff'/%3E%3Cpath d='M0 540L300 300L540 500L780 210L1200 560V675H0Z' fill='%231f4dcc'/%3E%3C/svg%3E";
  const compactImage = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='720' height='720'%3E%3Crect width='720' height='720' fill='%23dbe5ff'/%3E%3Ccircle cx='360' cy='330' r='190' fill='%231f4dcc'/%3E%3C/svg%3E";
  const responsiveMedia = base("responsive-media", "responsive-media", page([node({ nodeId: "media-story", tag: "section", role: "responsive-visual-story", classes: ["media-story"], attributes: { "aria-labelledby": "media-story-title" }, styles: sharedStyles.section, children: [node({ nodeId: "media-story-inner", tag: "div", role: "layout-container", classes: ["media-story__inner"], styles: { ...sharedStyles.inner, display: "grid", gap: "var(--space-l)", "grid-template-columns": "minmax(0, 2fr) minmax(16rem, 1fr)" }, conditionalStyles: stackAtMobile({ "grid-template-columns": "1fr" }), children: [node({ nodeId: "media-story-picture", tag: "picture", role: "responsive-picture", classes: ["media-story__picture"], styles: { display: "block" }, children: [node({ nodeId: "media-story-source", tag: "source", role: "mobile-image-source", classes: ["media-story__source"], attributes: { media: "(max-width: 47.99rem)", srcset: compactImage }, styles: {} }), node({ nodeId: "media-story-image", tag: "img", role: "meaningful-image", classes: ["media-story__image"], attributes: { src: wideImage, srcset: `${wideImage} 1200w`, sizes: "(max-width: 47.99rem) 100vw, 66vw", alt: "A planning landscape connecting evidence to production decisions", width: "1200", height: "675", loading: "eager", decoding: "async" }, styles: { display: "block", "inline-size": "100%", height: "auto", "border-radius": "var(--radius-m)" } })] }), node({ nodeId: "media-story-content", tag: "div", role: "content-stack", classes: ["media-story__content"], styles: { display: "grid", gap: "var(--space-m)", "align-content": "center" }, children: [node({ nodeId: "media-story-title", tag: "h1", role: "primary-heading", classes: ["media-story__title"], attributes: { id: "media-story-title" }, text: "One story, composed for every viewport", styles: sharedStyles.title }), node({ nodeId: "media-story-copy", tag: "p", role: "supporting-copy", classes: ["media-story__copy"], text: "Preserve art direction, intrinsic dimensions, alternative text, and responsive layout as separate semantic decisions.", styles: { "font-size": "var(--text-l)" } })] })] })] })]), [contract("media-story", "section", ["inner", "picture", "source", "image", "content", "title", "copy"])]);

  return [hero, features, pricing, faq, testimonial, navigation, form, dialog, longForm, responsiveMedia];
}
