import { join } from "node:path";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { prepareBenchmark } from "../src/research/prepare.ts";
import { evaluatePolicy } from "../src/research/evaluate.ts";
import { runResearch } from "../src/research/loop.ts";
import { defaultPolicy } from "../src/research/policy.ts";
import { distill } from "../src/distill/train.ts";

const root = await mkdtemp(join(tmpdir(), "gen2prod-acceptance-"));
const fixtures = join(root, "fixtures");
await prepareBenchmark({ root: fixtures, seed: 1337, countPerArchetype: 1 });
const evaluation = await evaluatePolicy({ manifestPath: join(fixtures, "manifest.json"), policy: defaultPolicy, split: "all", workDirectory: join(root, "evaluation") });
const requiredZero = ["criticalGateFailures", "contentBehaviorErrors", "semanticContractError", "accessibilityError", "visualLoss", "unaccountedDeclarations", "bemComponentError", "crossPageDrift", "idempotenceError"] as const;
for (const key of requiredZero) if (evaluation.fitness[key] !== 0) throw new Error(`Acceptance failed: ${key}=${evaluation.fitness[key]}`);
if (evaluation.mutationControlRecall !== 1) throw new Error(`Acceptance failed: mutation recall ${evaluation.mutationControlRecall}`);
const research = await runResearch({ manifestPath: join(fixtures, "manifest.json"), workspace: join(root, "workspace"), track: "policy", budget: 3, split: "validation", hiddenHoldoutEvery: 2 });
if (research.accepted < 1) throw new Error("Acceptance failed: autoresearch did not keep a measured improvement");
const distilled = await distill(join(root, "workspace", "research", "trajectories.jsonl"), join(root, "distilled"), "all");
if (!distilled.models.selector || !distilled.models.verifier || !distilled.models.planner) throw new Error("Acceptance failed: not all distilled models were produced");
if (distilled.dataset.preferences < 1) throw new Error("Acceptance failed: accepted/rejected preference pairs were not produced");
console.log(JSON.stringify({ ok: true, fixtures: evaluation.resourceAccounting.fixtureCount, fitness: evaluation.fitness, mutationControlRecall: evaluation.mutationControlRecall, research: { accepted: research.accepted, rejected: research.rejected, finalCost: research.finalFitness.normalizedComputeCost }, distillation: distilled.dataset }));
