import { describe, expect, test } from "bun:test";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { sha256 } from "../../src/core/hash.ts";
import type { CaptureResult } from "../../src/evidence/capture.ts";
import { discoverProject } from "../../src/project-adapters/discovery.ts";
import { parseProjectSource } from "../../src/project-adapters/registry.ts";
import { applyPreparedTextPatch, prepareTextPatch, projectOperationGraphHash } from "../../src/project-adapters/rewrite/text-edits.ts";
import { inventoryProjectStyles, planDeadStyleRemoval, planSharedScss, validateCompiledOwnedProjectScss, validateOwnedProjectScss } from "../../src/project-adapters/styles.ts";
import { ProjectPatchPlanSchema } from "../../src/schemas/project-adapters.ts";

describe("shared project SCSS and selector reachability", () => {
  test("keeps unrendered source branches, removes only source+render dead rules, and patches one owner", async () => {
    const root = await mkdtemp(join(tmpdir(), "g2p-project-styles-"));
    await Bun.write(join(root, "package.json"), JSON.stringify({ name: "styles", scripts: { build: "vite build" }, dependencies: { react: "19.0.0", vite: "7.0.0" } }));
    await Bun.write(join(root, "bun.lock"), "lock");
    await Bun.write(join(root, "src", "App.tsx"), 'export function App({show}){return <main className="live">{show && <p className="branch">Branch</p>}</main>}\n');
    const styleSource = '@use "tokens";\n.page { color: var(--old); }\n.live { color: red; }\n.branch { color: blue; }\n.render-only { color: green; }\n.dead { color: black; }\n';
    await Bun.write(join(root, "src", "app.scss"), styleSource);
    const discovery = await discoverProject(root);
    const project = await parseProjectSource(root, discovery);
    const capture: CaptureResult = { environment: { browser: "chromium", browserVersion: "fixture", os: "linux", deviceScaleFactor: 1, timezone: "UTC", locale: "en-US", fontSetHash: sha256("font"), colorScheme: "light", colorProfile: "sRGB" }, captures: [{ viewport: 800, viewportHeight: 600, theme: "light", state: "default", screenshot: "fixture.png", screenshotHash: sha256("image"), dom: [{ attributes: { class: "live render-only" } }], accessibilityTree: [], performance: {}, seo: {}, console: [] }] };
    const inventory = await inventoryProjectStyles(root, discovery.contract, project, capture);
    const status = Object.fromEntries(inventory.rules.map((rule) => [rule.selector, rule.reachable]));
    expect(status[".live"]).toBe("both");
    expect(status[".branch"]).toBe("source");
    expect(status[".render-only"]).toBe("rendered");
    expect(status[".dead"]).toBe("dead");
    const canonical = ".page {\n  color: var(--text-dark);\n\n  &__title {\n    margin-block: var(--space-m);\n  }\n}\n";
    expect(validateOwnedProjectScss(canonical, ["--text-dark", "--space-m"]).passed).toBeTrue();
    expect(validateOwnedProjectScss(canonical, ["--text-dark"]).unresolvedVariables).toEqual(["--space-m"]);
    const compiled = await validateCompiledOwnedProjectScss(canonical, ["--text-dark", "--space-m"]);
    expect(compiled.passed).toBeTrue();
    expect(compiled.tokenCoverage).toBe(1);
    expect(compiled.selectors.metrics.utilitySelectors).toBe(0);
    const styleOperation = await planSharedScss({ root, contract: discovery.contract, project, inventory, bemBlock: "page", canonicalScss: canonical, operationId: "style-page", registeredVariables: ["--text-dark", "--space-m"] });
    if (!styleOperation) throw new Error("Expected a style operation");
    const deadOperation = await planDeadStyleRemoval(root, inventory.rules.find((rule) => rule.selector === ".dead")!, "remove-dead");
    expect(planDeadStyleRemoval(root, inventory.rules.find((rule) => rule.selector === ".branch")!, "remove-branch")).rejects.toThrow("not proven dead");
    const operations = [styleOperation, deadOperation];
    const plan = ProjectPatchPlanSchema.parse({ schemaVersion: "0.1.0", planId: "styles", projectId: project.projectId, mode: "legacy-conversion", profile: "refactor", contractHash: project.contractHash, sourceProjectHash: project.sourceHash, canonicalOutputHash: sha256("canonical"), policyHash: sha256("policy"), operations, operationGraphHash: projectOperationGraphHash(operations), requiredActions: [], predictedChangedFiles: ["src/app.scss"], predictedChangedBytes: canonical.length });
    const prepared = await prepareTextPatch(root, discovery.contract, project, plan);
    await applyPreparedTextPatch(prepared);
    const output = await Bun.file(join(root, "src", "app.scss")).text();
    expect(output).toContain("&__title");
    expect(output).toContain(".branch");
    expect(output).not.toContain(".dead");
    expect(output.startsWith('@use "tokens";')).toBeTrue();
  });
});
